# Generated by Django 6.1 on 2026-08-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='loctions',
            new_name='loction',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profileing',
            new_name='profileimg',
        ),
    ]
