# Generated by Django 6.1 on 2026-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_memorablemoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(blank=True, default='blank-cover.png', null=True, upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
